openapi: 3.0.0
info:
  version: 1.0.0
  title: 女優図鑑
  description: 女優図鑑管理API
servers:
  - url: http://localhost:5000/api/system/
paths:
  /nice:
    post:
      tags:
        - System
      summary:
        いいね数確定API
      description: 女優毎のいいねを更新する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NiceRequest'
      responses:
        200:
          description: 正常応答
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NiceResponse'
        400:
          description: パラメーターエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: サーバー内部エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /mode_change:
    post:
      tags:
        - System
      summary:
        モード切替API
      description: 通常モード ⇔ メンテナンスモード切替を行う
      parameters:
        - in: header
          name: user-agent
          schema:
            type: string
          required: true
          description: ユーザーエージェント
          example: Example User
      responses:
        200:
          description: 正常応答
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModeChangeResponse'
        400:
          description: パラメーターエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: サーバー内部エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /version:
    get:
      tags:
        - System
      summary:
        バージョン取得API
      description:
        バージョンを取得
      responses:
        200:
          description: 正常応答
          content:
            application/json:
              schema:
                properties:
                  version:
                    type: string
                    example: "1.0.0"
components:
  schemas:
    NiceRequest:
      type: object
      properties:
        actressId:
          type: integer
          description: 女優ID
          example: 12345
        userId:
          type: string
          description: ユーザーID
          example: "00000001"
    NiceResponse:
      type: array
      items:
        type: object
        properties:
          actressId:
            type: integer
            description: 女優ID
            example: 12345
          niceCnt:
            type: integer
            description: 移行いいね数
            example: 1
    ModeChangeResponse:
      type: object
      properties:
        currentMode:
          type: string
          description: 現在のモード
          example: "通常モード"
    ErrorResponse:
      description: エラーオブジェクト
      type: object
      properties:
        message:
          description: エラーメッセージ
          type: string