build:
  maxIssues: 3
  weights:
    ForbiddenComment: 0
    MatchingDeclarationName: 1
    ReturnCount: 0
    TooGenericExceptionCaught: 0
    TooGenericExceptionThrown: 1
console-reports:
  active: true